repos:
- repo: https://github.com/executablebooks/mdformat
  rev: 08fba30538869a440b5059de90af03e3502e35fb  # frozen: 0.7.17
  hooks:
  - id: mdformat
    additional_dependencies:
    - mdformat-toc
    - mdformat-gfm
    - mdformat-black
- repo: https://github.com/asottile/yesqa
  rev: f2ae90cf9e1661ade79d0881186ce4fd7ba6ee79  # frozen: v1.5.0
  hooks:
  - id: yesqa
    additional_dependencies:
    - flake8-bugbear
    - flake8-builtins
    - flake8-comprehensions
- repo: https://github.com/PyCQA/isort
  rev: dbf82f2dd09ae41d9355bcd7ab69187a19e6bf2f  # frozen: 5.12.0
  hooks:
  - id: isort
- repo: https://github.com/psf/black
  rev: e87737140f32d3cd7c44ede75f02dcd58e55820e  # frozen: 23.9.1
  hooks:
  - id: black
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: f71fa2c1f9cf5cb705f73dffe4b21f7c61470ba9  # frozen: v4.4.0
  hooks:
  - id: check-yaml
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: 3a6eb0fadf60b3cccfd80bad9dbb6fae7e47b316  # frozen: v1.10.0
  hooks:
  - id: python-use-type-annotations
  - id: python-check-blanket-noqa
  - id: python-check-blanket-type-ignore
- repo: https://github.com/PyCQA/flake8
  rev: 10f4af6dbcf93456ba7df762278ae61ba3120dc6  # frozen: 6.1.0
  hooks:
  - id: flake8
    additional_dependencies:
    - flake8-bugbear
    - flake8-builtins
    - flake8-comprehensions
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 08cbc46b6e135adec84911b20e98e5bc52032152  # frozen: v1.5.1
  hooks:
  - id: mypy
    args: ["--scripts-are-modules"]
    additional_dependencies:
    - pytest
    - tomli
