repos:
- repo: https://github.com/executablebooks/mdformat
  rev: ff29be1a1ba8029d9375882aa2c812b62112a593  # frozen: 0.7.22
  hooks:
  - id: mdformat
    additional_dependencies:
    - mdformat-toc
    - mdformat-gfm
    - mdformat-black
- repo: https://github.com/asottile/yesqa
  rev: f2ae90cf9e1661ade79d0881186ce4fd7ba6ee79  # frozen: v1.5.0
  hooks:
  - id: yesqa
    additional_dependencies:
    - flake8-bugbear
    - flake8-builtins
    - flake8-comprehensions
- repo: https://github.com/PyCQA/isort
  rev: 0a0b7a830386ba6a31c2ec8316849ae4d1b8240d  # frozen: 6.0.0
  hooks:
  - id: isort
- repo: https://github.com/psf/black
  rev: 8a737e727ac5ab2f1d4cf5876720ed276dc8dc4b  # frozen: 25.1.0
  hooks:
  - id: black
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b  # frozen: v5.0.0
  hooks:
  - id: check-yaml
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: 3a6eb0fadf60b3cccfd80bad9dbb6fae7e47b316  # frozen: v1.10.0
  hooks:
  - id: python-use-type-annotations
  - id: python-check-blanket-noqa
  - id: python-check-blanket-type-ignore
- repo: https://github.com/PyCQA/flake8
  rev: e43806be3607110919eff72939fda031776e885a  # frozen: 7.1.1
  hooks:
  - id: flake8
    additional_dependencies:
    - flake8-bugbear
    - flake8-builtins
    - flake8-comprehensions
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: bbc3dc1f890007061f18f17e2334f216ea9e5df7  # frozen: v1.14.1
  hooks:
  - id: mypy
    args: ["--scripts-are-modules"]
    additional_dependencies:
    - pytest
    - tomli
